[project]
name = "sfml-test"
language = "CXX"
libraries = ["sfml-graphics", "sfml-window", "sfml-system"]
library_directories = []

[directories]
source_dir = "./src"
build_dir = "./build"
object_dir = "./obj"
[compiler.c]
command = "gcc"
flags = []

[compiler.cxx]
command = "g++"
flags = []
