[project]
name = 'sfml-test'
language = 'CXX'
libraries = [
    'sfml-graphics',
    'sfml-window',
    'sfml-system',
]
library_directories = []

[directories]
build_dir = './build'
object_dir = './obj'
source_dir = './src'

[compiler.c]
command = 'gcc'
flags = []

[compiler.cxx]
command = 'g++'
flags = []
