[project]
name = "olc-pge-test"
language = "CXX"
libraries = ["X11", "GL", "pthread", "png", "stdc++fs"]
library_directories = []

[directories]
source_dir = "./src"
build_dir = "./build"
object_dir = "./obj"
[compiler.c]
command = "gcc"
flags = []

[compiler.cxx]
command = "g++"
flags = []
